#set java path up to the Jre in JAVA_HOME
JAVA_HOME=/*ENTER JAVA HOME PATH UPTO JRE*/

#set NOGUI
NOGUI=true

#set DISCOVERONLY
DISCOVERONLY=true    

#set SILENTPATCH
SILENTPATCH=false

#set BACKWARDCOMPATIBILITY
BACKWARDCOMPATIBILITY=false
